spring.application.name=productservice
spring.datasource.username=root
spring.datasource.password=Revature@123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8081

spring.datasource.url=jdbc:mysql://mysql-db:3306/microservicesdb?createIfNotExists=true
eureka.client.service-url.defaultZone = http://servicediscovery:8761/eureka/
